### ISSUE TITLE
Id Property - long

### ISSUE THREAD

**Issue by cxs-mahendra** [NonFactors/MVC5.Datalist.Web#2]
Hi,

I have my entity Id property as `long`.
In the controller code, it throws following error 
`Datalist.DatalistException: ''Person.Id' property type has to be a string or an int.`

Can you please provide me some workaround for the above error.

Regards,
Mahendra

**Comment by Muchiachio** [comment]
Override `FilterByIds` and FilterByNotIds` to filter long values.
