### ISSUE TITLE
Javascript select event

### ISSUE THREAD

**Issue by ktngoykalolo** [NonFactors/MVC5.Datalist.Web#3]
hello,
big ups to the team creating this project! its incredibly useful!
I have a particular concern : 
how do I work with the select event of the datalist ? 
which event do I have to work with when selecting a value ? 
looking forward to a prompt feedback. 
kind regards!!

**Comment by Muchiachio** [comment]
What in particular do you need to do? `select` event is fired on value selection.

**Comment by ktngoykalolo** [comment]
I would like to browse to a value when I select a value. 
I will supply a specific link associated with the primary key of the data class.

**Comment by Muchiachio** [comment]
All selected data is stored in `data` variable:
```JS
$('.datalist').datalist({
    events: {
        select: function (e, data, triggerChanges) {
            if (data.length) { // something is selected
                browse(data[0].MyPropertyName); // use stored data to browse to
            }
        }
    }
});
```

**Comment by ktngoykalolo** [comment]
thanks for the help, the tip worked. 
i got another question though : 
when it queries the data, it does not return all of the data as it should, it just shows a specific number of rows, the query is not very accurate. 
is there a way to improve the results returned ?

**Comment by Muchiachio** [comment]
It returns paged data, you can change that from datalist's [paging configuration](http://mvc-datalist.azurewebsites.net/Datalist/PagingOptions).

**Comment by ktngoykalolo** [comment]
how do I change them ?

**Comment by Muchiachio** [comment]
Yes in the constructor or after creating it.
Your options have to be set before passing datalist instance to a html helper.

**Comment by ktngoykalolo** [comment]
I will try that and let you know.

**Comment by ktngoykalolo** [comment]
Hello @Muchiachio I tried looking at the paging as you requested, but it does not explain in details how to work with paging. 
- is there a way to navigate the pages with the autocomplete ? 
- is there a way to go beyond the 20 items cap for the autocomplete ?

**Comment by Muchiachio** [comment]
You can't navigate pages in autocomplete, or I just don't know a way to do it with jQuery's autocomplete.
You can pass custom [autocomplete options](http://mvc-datalist.azurewebsites.net/Datalist/Configuration) to change the [default cap](https://github.com/NonFactors/MVC5.Datalist/blob/cf4e688ba709f6ec0ad479d5fbbd8e7f66908ba0/src/Datalist/Scripts/MvcDatalist/mvc-datalist.js#L444).
