### ISSUE TITLE
NotSupportedException: The specified type member 'Id' is not supported in LINQ to Entities.

### ISSUE THREAD

**Issue by titobrasolin** [NonFactors/MVC5.Datalist.Web#8]
Two years after issue #4 (Database First Approach) I'm back to the same old project for some minor enhancements, but after upgrading all NuGet Packages I got the following error:

    NotSupportedException: The specified type member 'Id' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties are supported.]
    Microsoft.VisualBasic.CompilerServices.Container.InvokeMethod(Method TargetProcedure, Object[] Arguments, Boolean[] CopyBack, BindingFlags Flags) +187
    Microsoft.VisualBasic.CompilerServices.NewLateBinding.ObjectLateGet(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack) +300
    Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateGet(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack) +1303112
    Ticket.Controllers.TicketController.AllSoggetti(DatalistFilter filter) [...]

Here are a couple of lines of code:

    datalist = New SoggettiDatalist(Context) With {.Filter = filter}
    Return Json(datalist.GetData(), JsonRequestBehavior.AllowGet) ' <- The error happens here.

I still have no control over the classes from Entity Framework, so I added to the partial class "Soggetti" an "Id" property that wraps the "_SoggettiId" field, and everything worked until I updated the libraries.

@Muchiachio Do you think I should override "FilterByIds"? Or are there any better and more standard approach?

**Comment by Muchiachio** [comment]
Yes, you will have to override `FilterByIds` and probably `FilterByNotIds` too. Or you could introduce a view model and map it in `GetModels` method if you have no control over the model classes themselves.
